
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package JsonAnalizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMA = 7;
  public static final int STRING = 3;
  public static final int DOUBLE = 2;
  public static final int error = 1;
  public static final int LLAVE_AA = 4;
  public static final int DOSP = 6;
  public static final int LLAVE_CC = 5;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DOUBLE",
  "STRING",
  "LLAVE_AA",
  "LLAVE_CC",
  "DOSP",
  "COMA"
  };
}

